version: "3"

tasks:
  lint:
    cmd: golangci-lint run {{.CLI_ARGS}}

  test:
    cmd: go test -v -race ./...
    dir: "{{.CLI_ARGS}}"

  tag:push:
    cmds:
      - git tag {{.CLI_ARGS}}
      - git push origin {{.CLI_ARGS}} 